### ISSUE TITLE
Pretrained model

### ISSUE THREAD

**Issue by YiJun-Yang** [mhconradt/InceptionResNetV2#1]
Hi, 

Thank you very much for the implementation of InceptionResNetV2.

My major concern is whether there is the model pretrained on ImageNet for your implementation?

**Comment by mhconradt** [comment]
Hello, I forgot to deprecate this repo. I'd recommend you find another library for your research. [Here are some alternatives for image classification](https://huggingface.co/models?library=pytorch&pipeline_tag=image-classification&sort=downloads).
